### ISSUE TITLE
64-bit x86 Support

### ISSUE THREAD

**Issue by CWftw** [VKCOM/KNet#6]
Hi, we have noticed that this project does not include an x86_64 binary. This is required for Chromebooks and other devices. Crash report for reference:

`2021-11-17 14:12:33.413 6772-6772/com.example E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example, PID: 6772
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.example-4ObnE4hgI7tCiid5nvokZw==/base.apk"],nativeLibraryDirectories=[/data/app/com.example-4ObnE4hgI7tCiid5nvokZw==/lib/x86_64, /data/app/com.example-4ObnE4hgI7tCiid5nvokZw==/base.apk!/lib/x86_64, /system/lib64, /vendor/lib64]]] couldn't find "libcronet.93.0.4577.82.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at org.chromium.net.impl.CronetLibraryLoader.ensureInitialized(CronetLibraryLoader.java:71)
        at org.chromium.net.impl.CronetUrlRequestContext.<init>(CronetUrlRequestContext.java:154)
        at org.chromium.net.impl.NativeCronetEngineBuilderImpl.build(NativeCronetEngineBuilderImpl.java:32)
        at org.chromium.net.ExperimentalCronetEngine$Builder.build(ExperimentalCronetEngine.java:232)
        at com.vk.knet.cornet.CronetEngineBuilder.build(CronetEngineBuilder.kt:234)
        at com.vk.knet.cornet.experiment.CronetClient$Builder.cronetEngine(CronetClient.kt:507)
        at com.vk.knet.cornet.experiment.CronetClient$Builder.build$cronet_release(CronetClient.kt:440)
        at com.vk.knet.cornet.CronetKnetEngine$Builder.build$cronet_release(CronetKnetEngine.kt:82)
        at com.vk.knet.cornet.CronetKnetEngine$Companion.Build(CronetKnetEngine.kt:45)
        at com.example.Utils.KnetCronet.<clinit>(KnetCronet.kt:16)
        at com.example.Core.Application.onCreate(Application.java:156)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1167)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6130)
        at android.app.ActivityThread.access$1100(ActivityThread.java:201)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1725)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6971)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:865)`

**Comment by anchupin** [comment]
Fixed in repo. 
I'll publish x86_64 tomorrow to alpha05, thank you.)

**Comment by anchupin** [comment]
Done
